create table USER_PROFILES (
	up_user_id INT,
	up_dp VARCHAR(50),
	up_name VARCHAR(50),
	up_user_name VARCHAR(50),
	up_gender VARCHAR(50),
	up_date_joined DATE,
	up_preferred_categories VARCHAR(50),
	up_preferred_gender VARCHAR(50),
	up_contact_number VARCHAR(50),
	up_email VARCHAR(50),
	up_password VARCHAR(50),

	PRIMARY KEY(up_user_id),
	FOREIGN KEY (up_user_id) REFERENCES USERS(user_id)
);
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (1, 'http://dummyimage.com/167x100.png/cc0000/ffffff', 'Krystyna Tretwell', 'ktretwell0', 'Male', '3/23/2021', 'Comedy|Drama|Romance', 'Male', '288-652-0107', 'ktretwell0@sbwire.com', 'oYSBzAMDHYg');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (2, 'http://dummyimage.com/177x100.png/cc0000/ffffff', 'Leonid Jewell', 'ljewell1', 'Female', '5/24/2020', 'Comedy|Crime|Mystery', 'Male', '410-729-5004', 'ljewell1@goo.ne.jp', 'YE5puJZy');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (3, 'http://dummyimage.com/161x100.png/cc0000/ffffff', 'Barny Fonzone', 'bfonzone2', 'Female', '3/31/2021', 'Comedy|Musical', 'Male', '479-357-5011', 'bfonzone2@google.ca', 'ne19cV');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (4, 'http://dummyimage.com/152x100.png/5fa2dd/ffffff', 'Eduardo Bonicelli', 'ebonicelli3', 'Male', '12/12/2020', 'Drama|Mystery|Romance|Thriller', 'Male', '328-661-2894', 'ebonicelli3@opensource.org', 'Ymhs3b0dhWf');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (5, 'http://dummyimage.com/188x100.png/5fa2dd/ffffff', 'Binky Thebes', 'bthebes4', 'Male', '6/27/2020', 'Comedy|Crime|Drama', 'Male', '685-552-5702', 'bthebes4@eepurl.com', '7Wrwlq');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (6, 'http://dummyimage.com/245x100.png/ff4444/ffffff', 'Norbie Dorin', 'ndorin5', 'Female', '4/11/2021', 'Comedy', 'Female', '858-481-5988', 'ndorin5@miibeian.gov.cn', 'AdgZr424Gkp');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (7, 'http://dummyimage.com/186x100.png/cc0000/ffffff', 'Dianemarie Grady', 'dgrady6', 'Male', '9/29/2020', 'Thriller', 'Male', '513-151-1353', 'dgrady6@imgur.com', 'DfGufvJp');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (8, 'http://dummyimage.com/226x100.png/dddddd/000000', 'Fancie Windibank', 'fwindibank7', 'Female', '1/12/2021', 'Drama', 'Male', '943-984-8144', 'fwindibank7@cargocollective.com', 'kwLpSxkJ');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (9, 'http://dummyimage.com/231x100.png/cc0000/ffffff', 'Wally Keyse', 'wkeyse8', 'Female', '3/25/2021', 'Drama', 'Male', '391-193-6324', 'wkeyse8@dailymotion.com', 'W5Y67Ks4Tt');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (10, 'http://dummyimage.com/122x100.png/cc0000/ffffff', 'Inga Bare', 'ibare9', 'Female', '9/1/2020', 'Drama', 'Female', '320-256-7867', 'ibare9@domainmarket.com', 'xrSkUuMg');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (11, 'http://dummyimage.com/218x100.png/5fa2dd/ffffff', 'Leodora Brevitt', 'lbrevitta', 'Male', '1/3/2021', 'Drama|Thriller|War', 'Male', '247-877-2738', 'lbrevitta@narod.ru', '08pCkSTgk6RN');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (12, 'http://dummyimage.com/218x100.png/ff4444/ffffff', 'Stern Cowin', 'scowinb', 'Female', '11/2/2020', 'Drama|Horror|Thriller', 'Female', '302-949-4076', 'scowinb@shinystat.com', 'BqLnRPYz2');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (13, 'http://dummyimage.com/179x100.png/5fa2dd/ffffff', 'Hulda Dalliwater', 'hdalliwaterc', 'Female', '1/26/2021', 'Drama', 'Male', '902-600-9499', 'hdalliwaterc@youku.com', 'aZYOWx5o8');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (14, 'http://dummyimage.com/198x100.png/ff4444/ffffff', 'Thadeus Colbertson', 'tcolbertsond', 'Female', '3/30/2021', 'Sci-Fi', 'Female', '833-330-5464', 'tcolbertsond@paginegialle.it', 'mSOBkfT');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (15, 'http://dummyimage.com/104x100.png/ff4444/ffffff', 'Raychel Yoell', 'ryoelle', 'Female', '6/4/2020', 'Documentary', 'Male', '521-544-0044', 'ryoelle@addtoany.com', 'DymeOaDZx');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (16, 'http://dummyimage.com/152x100.png/ff4444/ffffff', 'Jareb Blaney', 'jblaneyf', 'Female', '9/10/2020', 'Action|Thriller', 'Female', '630-965-7027', 'jblaneyf@topsy.com', 'qpxQui');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (17, 'http://dummyimage.com/188x100.png/cc0000/ffffff', 'Dominik Romero', 'dromerog', 'Female', '2/23/2021', 'Comedy|Crime|Drama|Horror|Mystery|Romance|Thriller', 'Female', '383-906-9811', 'dromerog@indiegogo.com', 'uOgoAZuB');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (18, 'http://dummyimage.com/127x100.png/cc0000/ffffff', 'Shamus Passo', 'spassoh', 'Female', '3/14/2021', 'Comedy', 'Female', '435-686-9078', 'spassoh@qq.com', 'HKg32Tvazdj');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (19, 'http://dummyimage.com/113x100.png/ff4444/ffffff', 'Lucina Wornham', 'lwornhami', 'Female', '11/20/2020', 'Action|Fantasy|Sci-Fi', 'Female', '522-784-6491', 'lwornhami@sitemeter.com', 'J6JcLSCaYwq');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (20, 'http://dummyimage.com/178x100.png/5fa2dd/ffffff', 'Nell Spurnier', 'nspurnierj', 'Female', '2/27/2021', 'Action|Drama|Musical', 'Female', '334-234-0217', 'nspurnierj@studiopress.com', 'Khes6r8e');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (21, 'http://dummyimage.com/192x100.png/ff4444/ffffff', 'Lynnea Basset', 'lbassetk', 'Male', '8/6/2020', 'Drama|Mystery|Western', 'Female', '617-758-9083', 'lbassetk@shinystat.com', 'pDk0WRjPfhO');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (22, 'http://dummyimage.com/141x100.png/ff4444/ffffff', 'Mathilda Lanegran', 'mlanegranl', 'Male', '4/17/2021', 'Comedy|Musical|Romance|Western', 'Female', '875-759-9629', 'mlanegranl@shareasale.com', 'JQkjn4');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (23, 'http://dummyimage.com/152x100.png/ff4444/ffffff', 'Law Kingh', 'lkinghm', 'Female', '10/3/2020', 'Drama', 'Male', '214-357-4941', 'lkinghm@163.com', 'mToLiqc');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (24, 'http://dummyimage.com/198x100.png/dddddd/000000', 'Cletus Adanet', 'cadanetn', 'Male', '7/12/2020', 'Drama', 'Male', '181-778-5352', 'cadanetn@arizona.edu', 'RTOXPVhMG36');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (25, 'http://dummyimage.com/177x100.png/dddddd/000000', 'Darell Grenshields', 'dgrenshieldso', 'Female', '7/15/2020', 'Action|Crime|Thriller', 'Male', '968-427-4535', 'dgrenshieldso@europa.eu', '7npgy8');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (26, 'http://dummyimage.com/126x100.png/dddddd/000000', 'Trumaine Showers', 'tshowersp', 'Female', '1/7/2021', 'Drama', 'Female', '720-901-7066', 'tshowersp@senate.gov', '0J92gC');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (27, 'http://dummyimage.com/107x100.png/cc0000/ffffff', 'Christian Boate', 'cboateq', 'Male', '5/13/2021', 'Horror', 'Female', '377-462-4744', 'cboateq@bizjournals.com', 'IQS87ikXII6');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (28, 'http://dummyimage.com/220x100.png/cc0000/ffffff', 'Chere Edrich', 'cedrichr', 'Male', '3/22/2021', 'Comedy|Drama|Mystery', 'Female', '534-708-7642', 'cedrichr@dot.gov', 'k1OQaf7ta');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (29, 'http://dummyimage.com/238x100.png/5fa2dd/ffffff', 'Fidole Francke', 'ffranckes', 'Female', '2/6/2021', 'Drama|War', 'Female', '529-182-4734', 'ffranckes@i2i.jp', 'UFEU5KD5');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (30, 'http://dummyimage.com/184x100.png/dddddd/000000', 'Patrizius D''Elias', 'pdeliast', 'Female', '7/23/2020', 'Drama', 'Female', '240-232-3598', 'pdeliast@wikimedia.org', '7SBiEhysX70');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (31, 'http://dummyimage.com/177x100.png/cc0000/ffffff', 'Emmott Dana', 'edanau', 'Male', '1/7/2021', 'Documentary', 'Male', '314-950-5163', 'edanau@fastcompany.com', 'SWTn3N9daa9X');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (32, 'http://dummyimage.com/196x100.png/dddddd/000000', 'Hermie Petruska', 'hpetruskav', 'Male', '2/27/2021', 'Drama', 'Male', '352-693-8886', 'hpetruskav@mozilla.org', 'PRE9amf2S');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (33, 'http://dummyimage.com/158x100.png/dddddd/000000', 'Anatol McElhinney', 'amcelhinneyw', 'Female', '4/20/2021', 'Comedy|Romance', 'Male', '767-683-9335', 'amcelhinneyw@answers.com', 'joIfAeI');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (34, 'http://dummyimage.com/118x100.png/dddddd/000000', 'Phillipe Deakan', 'pdeakanx', 'Female', '9/21/2020', 'Comedy', 'Female', '637-760-4985', 'pdeakanx@amazon.co.jp', 'Y8FRB5SaR');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (35, 'http://dummyimage.com/140x100.png/cc0000/ffffff', 'Crysta Cammis', 'ccammisy', 'Male', '7/15/2020', 'Action|Crime|Drama', 'Male', '999-887-0680', 'ccammisy@canalblog.com', '9kdRXty');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (36, 'http://dummyimage.com/171x100.png/cc0000/ffffff', 'Hersh Sholem', 'hsholemz', 'Male', '3/14/2021', 'Comedy', 'Female', '448-543-8594', 'hsholemz@gravatar.com', 'vsC7PrJ');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (37, 'http://dummyimage.com/179x100.png/ff4444/ffffff', 'Dianemarie MacQuist', 'dmacquist10', 'Female', '9/3/2020', 'Thriller', 'Male', '672-746-4674', 'dmacquist10@usgs.gov', 'tInNUdkGT8');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (38, 'http://dummyimage.com/162x100.png/ff4444/ffffff', 'Shay Pershouse', 'spershouse11', 'Male', '12/3/2020', 'Action|Crime', 'Male', '288-712-4459', 'spershouse11@unicef.org', '7rezYF');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (39, 'http://dummyimage.com/239x100.png/cc0000/ffffff', 'Bettye Benmore', 'bbenmore12', 'Male', '12/28/2020', 'Drama|Romance', 'Female', '697-851-8067', 'bbenmore12@dion.ne.jp', 'kBjMznRd');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (40, 'http://dummyimage.com/177x100.png/cc0000/ffffff', 'Laryssa McAree', 'lmcaree13', 'Male', '6/14/2020', 'Documentary', 'Female', '744-148-0502', 'lmcaree13@whitehouse.gov', '1u9EblFwThK');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (41, 'http://dummyimage.com/214x100.png/5fa2dd/ffffff', 'Bab Goold', 'bgoold14', 'Female', '10/30/2020', 'Action|Thriller', 'Male', '446-859-5367', 'bgoold14@studiopress.com', 'B6OAX7');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (42, 'http://dummyimage.com/101x100.png/ff4444/ffffff', 'Marj Polkinghorne', 'mpolkinghorne15', 'Male', '11/23/2020', 'Thriller', 'Female', '121-114-4497', 'mpolkinghorne15@ca.gov', 'EJjdRsOtis');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (43, 'http://dummyimage.com/127x100.png/5fa2dd/ffffff', 'Winnie Apedaile', 'wapedaile16', 'Male', '9/30/2020', 'Drama', 'Female', '204-668-0409', 'wapedaile16@aboutads.info', 'fdPujfPwU');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (44, 'http://dummyimage.com/225x100.png/ff4444/ffffff', 'Penelopa Gindghill', 'pgindghill17', 'Female', '6/7/2020', 'Drama|Horror|Mystery|Romance|Thriller', 'Male', '211-779-0050', 'pgindghill17@cnbc.com', 'CBZWuM');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (45, 'http://dummyimage.com/226x100.png/dddddd/000000', 'Paolina Borsnall', 'pborsnall18', 'Male', '3/17/2021', 'Drama|Thriller', 'Male', '984-515-6671', 'pborsnall18@zimbio.com', 'GxmxOls0mnm');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (46, 'http://dummyimage.com/190x100.png/cc0000/ffffff', 'Armin Warrick', 'awarrick19', 'Male', '4/9/2021', 'Action|Drama', 'Male', '825-614-9322', 'awarrick19@icq.com', 'UK6wArWRE');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (47, 'http://dummyimage.com/223x100.png/dddddd/000000', 'Marlena Robinet', 'mrobinet1a', 'Female', '1/30/2021', 'Horror|Thriller', 'Male', '408-291-8371', 'mrobinet1a@npr.org', 'ku5LhTPIHC');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (48, 'http://dummyimage.com/102x100.png/5fa2dd/ffffff', 'Kippy Hedden', 'khedden1b', 'Male', '4/26/2021', 'Drama|Romance', 'Female', '286-352-5692', 'khedden1b@eventbrite.com', 'cHUUBgr');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (49, 'http://dummyimage.com/116x100.png/ff4444/ffffff', 'Biddie Giacomello', 'bgiacomello1c', 'Female', '5/29/2020', 'Drama', 'Female', '663-289-2957', 'bgiacomello1c@delicious.com', 'a2bClq');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (50, 'http://dummyimage.com/195x100.png/dddddd/000000', 'Crin MacKay', 'cmackay1d', 'Male', '6/25/2020', 'Adventure|Animation|Children|Comedy|Fantasy', 'Female', '303-226-7602', 'cmackay1d@feedburner.com', 'ERzaMfax');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (51, 'http://dummyimage.com/209x100.png/cc0000/ffffff', 'Fidel Matthieson', 'fmatthieson1e', 'Male', '2/2/2021', 'Action|Crime|Drama', 'Male', '366-480-7015', 'fmatthieson1e@edublogs.org', 'fA466DyYBvK');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (52, 'http://dummyimage.com/243x100.png/cc0000/ffffff', 'Georgianna Schruyers', 'gschruyers1f', 'Male', '3/10/2021', 'Action|Adventure|Crime|Drama|Thriller', 'Female', '687-989-7789', 'gschruyers1f@yahoo.com', 'eQfPc6dURcO');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (53, 'http://dummyimage.com/105x100.png/ff4444/ffffff', 'Allx Farreil', 'afarreil1g', 'Male', '6/11/2020', 'Drama', 'Male', '570-803-4144', 'afarreil1g@reference.com', 'RO3nj1P2j');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (54, 'http://dummyimage.com/245x100.png/ff4444/ffffff', 'Amargo Ivanishchev', 'aivanishchev1h', 'Female', '7/9/2020', 'Adventure|Comedy|Sci-Fi', 'Male', '385-601-9159', 'aivanishchev1h@wordpress.org', 'c5oOhO');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (55, 'http://dummyimage.com/158x100.png/ff4444/ffffff', 'Georas Westwick', 'gwestwick1i', 'Male', '11/22/2020', 'Drama', 'Male', '567-530-0458', 'gwestwick1i@cnn.com', 'eAoesfb');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (56, 'http://dummyimage.com/180x100.png/cc0000/ffffff', 'Sidonia Boshier', 'sboshier1j', 'Female', '12/31/2020', 'Documentary', 'Male', '326-444-3820', 'sboshier1j@slashdot.org', 'JDsNiiZ');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (57, 'http://dummyimage.com/236x100.png/5fa2dd/ffffff', 'Ewan Whitlock', 'ewhitlock1k', 'Female', '1/21/2021', 'Drama', 'Male', '834-771-2810', 'ewhitlock1k@oracle.com', 'rvMg31z');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (58, 'http://dummyimage.com/119x100.png/cc0000/ffffff', 'Marysa Coppen', 'mcoppen1l', 'Male', '6/13/2020', 'Drama', 'Female', '454-279-2790', 'mcoppen1l@google.co.uk', 'Ob31D4H1VTb');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (59, 'http://dummyimage.com/139x100.png/ff4444/ffffff', 'Gwennie Seleway', 'gseleway1m', 'Female', '4/19/2021', 'Action|Mystery', 'Female', '179-327-8534', 'gseleway1m@ifeng.com', 'QSxq7R');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (60, 'http://dummyimage.com/201x100.png/5fa2dd/ffffff', 'Jenine MacTrusty', 'jmactrusty1n', 'Male', '2/7/2021', 'Action|Adventure|War', 'Male', '164-947-6662', 'jmactrusty1n@bandcamp.com', 'Dt2EyZ5ov3fE');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (61, 'http://dummyimage.com/158x100.png/dddddd/000000', 'Graig Feeham', 'gfeeham1o', 'Male', '9/5/2020', 'Children|Documentary|IMAX', 'Female', '884-878-0250', 'gfeeham1o@discuz.net', 'cHhwx2');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (62, 'http://dummyimage.com/218x100.png/cc0000/ffffff', 'Terrel Hamal', 'thamal1p', 'Female', '10/29/2020', 'Children|Comedy', 'Male', '145-892-0619', 'thamal1p@amazon.de', 'OvrNfH');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (63, 'http://dummyimage.com/193x100.png/dddddd/000000', 'Herminia Furtado', 'hfurtado1q', 'Male', '12/16/2020', 'Horror|Thriller', 'Female', '622-804-3847', 'hfurtado1q@utexas.edu', 'YynMYOyuZj43');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (64, 'http://dummyimage.com/200x100.png/dddddd/000000', 'Dory Loram', 'dloram1r', 'Female', '10/19/2020', 'Adventure|Children|Comedy', 'Female', '694-779-3701', 'dloram1r@spotify.com', 'BpwKBFn');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (65, 'http://dummyimage.com/127x100.png/cc0000/ffffff', 'Pat Brabender', 'pbrabender1s', 'Female', '4/22/2021', 'Adventure|Animation|Children|Comedy|Fantasy|IMAX', 'Female', '775-885-4598', 'pbrabender1s@guardian.co.uk', 'tyn92POvHSJ');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (66, 'http://dummyimage.com/122x100.png/dddddd/000000', 'Kenny M''Quharg', 'kmquharg1t', 'Male', '12/3/2020', 'Drama', 'Male', '508-603-4299', 'kmquharg1t@forbes.com', 'htDScGpx');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (67, 'http://dummyimage.com/149x100.png/5fa2dd/ffffff', 'Oralie Lemmen', 'olemmen1u', 'Male', '6/2/2020', 'Crime|Drama|Romance', 'Male', '208-920-4202', 'olemmen1u@tinyurl.com', 'exxoUK');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (68, 'http://dummyimage.com/125x100.png/5fa2dd/ffffff', 'Myron Drains', 'mdrains1v', 'Male', '10/2/2020', 'Comedy|Drama|Romance', 'Female', '602-853-5451', 'mdrains1v@pcworld.com', 'YTsanV');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (69, 'http://dummyimage.com/153x100.png/ff4444/ffffff', 'Meghann Edgler', 'medgler1w', 'Male', '4/9/2021', 'Sci-Fi', 'Female', '754-925-2249', 'medgler1w@barnesandnoble.com', 'dCDCPnY');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (70, 'http://dummyimage.com/108x100.png/5fa2dd/ffffff', 'Kasey Puddicombe', 'kpuddicombe1x', 'Male', '6/10/2020', '(no genres listed)', 'Female', '875-158-2307', 'kpuddicombe1x@who.int', 'kegbut');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (71, 'http://dummyimage.com/183x100.png/cc0000/ffffff', 'Alair Agett', 'aagett1y', 'Male', '11/21/2020', 'Drama|Romance', 'Male', '620-132-6104', 'aagett1y@webeden.co.uk', '8iTKtR3RYMQ');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (72, 'http://dummyimage.com/186x100.png/dddddd/000000', 'Maisey Notton', 'mnotton1z', 'Female', '9/28/2020', 'Horror|Thriller', 'Female', '488-671-2760', 'mnotton1z@gov.uk', 'JW7JKgDKdcHi');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (73, 'http://dummyimage.com/153x100.png/ff4444/ffffff', 'Terrijo O''Daly', 'todaly20', 'Female', '11/9/2020', 'Drama|Romance|War', 'Female', '107-155-5959', 'todaly20@virginia.edu', 'QYXYVKYwD9z');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (74, 'http://dummyimage.com/167x100.png/cc0000/ffffff', 'Alexandros Tunnow', 'atunnow21', 'Female', '9/30/2020', 'Horror', 'Male', '957-671-8729', 'atunnow21@vkontakte.ru', 'xddFf0Z');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (75, 'http://dummyimage.com/202x100.png/5fa2dd/ffffff', 'Hercules Fever', 'hfever22', 'Female', '5/15/2021', 'Adventure|Romance|Western', 'Male', '956-296-8297', 'hfever22@photobucket.com', 'iOjqq06l9V');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (76, 'http://dummyimage.com/186x100.png/ff4444/ffffff', 'Gerrilee Maltby', 'gmaltby23', 'Male', '1/10/2021', 'Action|Adventure|Crime|Thriller', 'Male', '565-794-6160', 'gmaltby23@tripadvisor.com', 'S94HwaZA');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (77, 'http://dummyimage.com/151x100.png/ff4444/ffffff', 'Seline Goldie', 'sgoldie24', 'Male', '7/3/2020', 'Comedy', 'Male', '255-116-9568', 'sgoldie24@pbs.org', 'l7QzAM5aP');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (78, 'http://dummyimage.com/239x100.png/dddddd/000000', 'Wyndham Kleiner', 'wkleiner25', 'Female', '11/23/2020', 'Drama|Romance', 'Female', '520-591-1091', 'wkleiner25@live.com', 'RL7Sex');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (79, 'http://dummyimage.com/248x100.png/cc0000/ffffff', 'Meagan Iglesiaz', 'miglesiaz26', 'Female', '3/22/2021', 'Horror|Mystery|Thriller', 'Female', '641-385-9749', 'miglesiaz26@wikia.com', '8v1DQS');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (80, 'http://dummyimage.com/168x100.png/5fa2dd/ffffff', 'Earl Monni', 'emonni27', 'Male', '12/31/2020', 'Documentary', 'Female', '266-255-7525', 'emonni27@privacy.gov.au', 'vmGzEhOU');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (81, 'http://dummyimage.com/225x100.png/5fa2dd/ffffff', 'Vivian Jodrellec', 'vjodrellec28', 'Male', '4/4/2021', 'Comedy', 'Female', '287-871-9918', 'vjodrellec28@state.gov', 'fC0jEWs');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (82, 'http://dummyimage.com/233x100.png/cc0000/ffffff', 'Cherilynn Hoy', 'choy29', 'Male', '3/28/2021', 'Comedy|Drama', 'Female', '453-571-9014', 'choy29@yellowpages.com', 'jnBjTK5');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (83, 'http://dummyimage.com/145x100.png/dddddd/000000', 'Erick Batiste', 'ebatiste2a', 'Male', '6/4/2020', 'Animation', 'Male', '706-973-4030', 'ebatiste2a@deliciousdays.com', 'wccH3ff8W');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (84, 'http://dummyimage.com/160x100.png/5fa2dd/ffffff', 'Ysabel Espinha', 'yespinha2b', 'Female', '10/25/2020', 'Comedy|Horror', 'Female', '274-831-8228', 'yespinha2b@slate.com', 'e7OR0aipA');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (85, 'http://dummyimage.com/174x100.png/ff4444/ffffff', 'Leeland Victoria', 'lvictoria2c', 'Female', '6/3/2020', 'Drama', 'Male', '250-689-7256', 'lvictoria2c@utexas.edu', 'WcOs9Bm5Z');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (86, 'http://dummyimage.com/137x100.png/ff4444/ffffff', 'Thorn Bulled', 'tbulled2d', 'Male', '7/17/2020', 'Children|Comedy', 'Male', '959-666-3631', 'tbulled2d@reverbnation.com', 'HbXHxu8zL');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (87, 'http://dummyimage.com/191x100.png/dddddd/000000', 'Alden Chetham', 'achetham2e', 'Female', '7/6/2020', 'Crime|Drama|Thriller', 'Male', '655-899-2326', 'achetham2e@guardian.co.uk', '6v6gLQqu');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (88, 'http://dummyimage.com/234x100.png/5fa2dd/ffffff', 'Quintina MacRitchie', 'qmacritchie2f', 'Male', '9/2/2020', 'Animation|Children|Fantasy|Musical', 'Male', '587-789-1903', 'qmacritchie2f@techcrunch.com', 'f62voJK');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (89, 'http://dummyimage.com/195x100.png/ff4444/ffffff', 'Mariette Rubinsky', 'mrubinsky2g', 'Male', '10/8/2020', 'Drama|Thriller', 'Male', '145-507-1026', 'mrubinsky2g@twitpic.com', '91AZzD1rEb');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (90, 'http://dummyimage.com/120x100.png/cc0000/ffffff', 'Thadeus Newbold', 'tnewbold2h', 'Male', '9/2/2020', 'Drama|Romance', 'Female', '522-785-4959', 'tnewbold2h@usnews.com', '7FMAO6TRr');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (91, 'http://dummyimage.com/194x100.png/5fa2dd/ffffff', 'Bondie Pender', 'bpender2i', 'Female', '10/27/2020', 'Drama', 'Male', '530-333-7902', 'bpender2i@tinypic.com', 'y0C6iG');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (92, 'http://dummyimage.com/175x100.png/ff4444/ffffff', 'Della Tournie', 'dtournie2j', 'Female', '9/23/2020', 'Action|Drama|Horror', 'Female', '412-678-6446', 'dtournie2j@discuz.net', 'g32mzjFlr3');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (93, 'http://dummyimage.com/123x100.png/5fa2dd/ffffff', 'Belvia Allwright', 'ballwright2k', 'Male', '12/29/2020', 'Action|War', 'Female', '129-729-5345', 'ballwright2k@cbc.ca', 'zpqo5cckpcCf');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (94, 'http://dummyimage.com/101x100.png/dddddd/000000', 'Darya Dermot', 'ddermot2l', 'Female', '10/29/2020', 'Comedy', 'Male', '764-994-5501', 'ddermot2l@ask.com', 'z921BXwfDik');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (95, 'http://dummyimage.com/155x100.png/dddddd/000000', 'Josee Ringer', 'jringer2m', 'Male', '11/27/2020', 'Horror|Thriller', 'Female', '942-849-6365', 'jringer2m@cnet.com', '6tyL2z1ODH');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (96, 'http://dummyimage.com/236x100.png/ff4444/ffffff', 'Delcina Allwood', 'dallwood2n', 'Female', '4/20/2021', 'Drama|Musical|Romance', 'Male', '116-809-7413', 'dallwood2n@4shared.com', 'F0FKVG');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (97, 'http://dummyimage.com/201x100.png/ff4444/ffffff', 'Garold Pencost', 'gpencost2o', 'Male', '7/28/2020', 'Horror|Thriller', 'Male', '376-247-1396', 'gpencost2o@godaddy.com', '5Wi4enhE');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (98, 'http://dummyimage.com/226x100.png/5fa2dd/ffffff', 'Lelia Dykas', 'ldykas2p', 'Female', '4/20/2021', 'Thriller', 'Female', '451-162-5449', 'ldykas2p@google.com.br', 'heCbMufhqr');
insert into USER_PROFILES (up_user_id, up_dp, up_name, up_user_name, up_gender, up_date_joined, up_preferred_categories, up_preferred_gender, up_contact_number, up_email, up_password) values (99, 'http://dummyimage.com/179x100.png/dddddd/000000', 'Shurlocke Vossgen', 'svossgen2q', 'Male', '7/19/2020', 'Adventure|Animation|Children', 'Female', '478-371-6177', 'svossgen2q@github.com', 'nir44q3ojd');
